# fix compdef errors
autoload -Uz compinit
compinit -i

# dotfiles zsh directory, to be set by install script
dotfilesZsh=/home/james/src/dotfiles/zsh

source $dotfilesZsh/antidote/antidote.zsh

zstyle ':antidote:bundle' file $dotfilesZsh/zsh_plugins.txt
antidote load

source $dotfilesZsh/aliases.sh

# enable command history saving
HISTFILE=$HOME/.zsh_history
HISTSIZE=100000
SAVEHIST=$HISTSIZE

# enable auto-cd
setopt autocd

# set up fzf
export FZF_DEFAULT_OPTS="--bind='ctrl-o:execute(subl {})+abort'"
[ -f /usr/share/fzf/shell/key-bindings.zsh ] && source /usr/share/fzf/shell/key-bindings.zsh

# add warning before using rm
unsetopt RM_STAR_SILENT

# fix delete key
bindkey "^[[3~" delete-char

# fix home and end
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line

# disable .net cli telemetry
export DOTNET_CLI_TELEMETRY_OPTOUT=1

# pnpm
export PNPM_HOME="/home/james/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end