# fix compdef errors
autoload -Uz compinit
compinit -i

# dotfiles zsh directory, to be set by install script
dotfilesZsh=/home/james/src/dotfiles/zsh

source $dotfilesZsh/zsh_plugins.sh
source $dotfilesZsh/aliases.sh

# enable command history saving
HISTFILE=$HOME/.zsh_history
HISTSIZE=100000
SAVEHIST=$HISTSIZE

# enable auto-cd
setopt autocd

# theme customisation
SPACESHIP_PROMPT_ADD_NEWLINE="false" # disable newline before prompt

# set up fzf
[ -f /usr/share/fzf/shell/key-bindings.zsh ] && source /usr/share/fzf/shell/key-bindings.zsh

# add warning before using rm
unsetopt RM_STAR_SILENT

# fix delete key
bindkey "^[[3~" delete-char

# fix home and end
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line

# disable .net cli telemetry
export DOTNET_CLI_TELEMETRY_OPTOUT=1