# dotfiles zsh directory, to be set by install script
dotfilesZsh=/home/jtattersall/src/dotfiles/zsh

source $dotfilesZsh/zsh_plugins.sh
source $dotfilesZsh/aliases.sh

# enable command history saving
HISTFILE=$HOME/.zsh_history
HISTSIZE=100000
SAVEHIST=$HISTSIZE

# enable auto-cd
setopt autocd

# theme customisation
SPACESHIP_PROMPT_ADD_NEWLINE="false" # disable newline before prompt

# set up fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# add warning before using rm
unsetopt RM_STAR_SILENT